### ISSUE TITLE
Lua Diagnostics warning on remote.call usage

### ISSUE THREAD

**Issue by muppet9010** [JanSharp/FactorioSumnekoLuaPlugin#1]
Any idea if this is a plugin issue or a setting required in the Sumneko Lua extension?
I tried adding it to a few global lists, both the field and with its remote object parent, but to no avail.

Code line:
`local wagonsToIgnore = remote.call("railway_tunnel", "get_temporary_carriage_names")`

Warning message: 
`Undefined field '__all_remote_interfaces'.`

Full warning details:
```
{
	"resource": "/e:/Home/Projects/Factorio Modding/Factorio-Railway-Tunnel/scripts/test-functions.lua",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": "undefined-field",
	"severity": 4,
	"message": "Undefined field `__all_remote_interfaces`.",
	"source": "Lua Diagnostics.",
	"startLineNumber": 192,
	"startColumn": 35,
	"endLineNumber": 192,
	"endColumn": 39
}
```

**Comment by JanSharp** [comment]
Oh i see what happened there, `remote` now has the type `LuaRemote` which doesn't have a field `__all_remote_interfaces` which is [what the plugin uses](https://github.com/JanSharp/FactorioSumnekoLuaPlugin#remotes).

The best solution doesn't come to mind right away but i need to push an update anyway so this will be fixed soon. (Most likely later today)

In the mean time you'll either have to [disable the plugin for the file](https://github.com/JanSharp/FactorioSumnekoLuaPlugin#help-it-broke), deal with it or find some other solution.

**Comment by JanSharp** [comment]
Alright it got a bit late but it's fixed now and pushed to master.
Feel free to reopen the issue if it (for some odd reason) doesn't work for you :)

**Comment by muppet9010** [comment]
yup solved the issue here as well, nice
