### ISSUE TITLE
Breaking changes

### ISSUE THREAD

**Issue by sumneko** [JanSharp/FactorioSumnekoLuaPlugin#2]
`config.config.XXX.XXX` has changed to `config.get 'Lua.XXX.XXX'`

**Comment by JanSharp** [comment]
Oh thank you for letting me know. I consider that part of the plugin to be pure hacks so i'm surprised you'd be the one to tell me about it, but i appreciate it of course :)

Fixed 👍

**Comment by sumneko** [comment]
I found it in the telemetry log: http://119.45.194.183/ (I'm not sure if you can open this site, it is a Chinese IP)

**Comment by JanSharp** [comment]
I see. Neat, i can open it as well, yes.
